version: '2'

services:
  frontend:
    image: nginx:1.11-alpine
    volumes:
      - "./code:/var/www/laravel:ro"
      - "./configs/nginx:/etc/nginx/conf.d:ro"
    depends_on:
      - backend
    links:
      - backend
    ports:
      - "5000:80"
  backend:
    build: .
    volumes:
      - "./code:/var/www/laravel"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_DATABASE: forge
      DB_USERNAME: forge
      DB_PASSWORD: forge
      BROADCAST_DRIVER: redis
      QUEUE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_HOST: redis
    depends_on:
      - mysql
      - redis
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis:/data
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: forge
      MYSQL_USER: forge
      MYSQL_PASSWORD: forge
    volumes:
      - mysql:/var/lib/mysql

volumes:
  redis:
  mysql:
